name: easy_task_flow
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.0
  firebase_messaging: ^15.0.1
  firebase_dynamic_links: ^6.0.0

  # Google APIs
  google_sign_in: ^6.2.1
  googleapis: ^13.1.0
  googleapis_auth: ^1.6.0
  http: ^1.1.0
  url_launcher: ^6.3.0

  # Monetization
  google_mobile_ads: ^5.1.0

  # State Management
  flutter_riverpod: ^2.5.1

  # Utilities
  uuid: ^4.4.0
  file_picker: ^8.0.0+1
  table_calendar: ^3.1.0
  share_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
